spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # lb: Load Balancer
          predicates:
            - Path=/user/**
          filters: # 요청을 처리하기 전에 적용할 필터 정의
            # StripPrefix=1: 요청 경로에서 첫 번째 경로 세그먼트를 제거
            # ex) /user/profile -> /profile
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

  datasource:
    url: jdbc:postgresql://localhost:5432/do_develop?currentSchema=carrot
    driver-class-name: org.postgresql.Driver
    username:
    password:
