spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/do_develop?currentSchema=msa
    username:
    password:

  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8082


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8080/eureka
  instance:
      prefer-ip-address: true